#!/usr/bin/env python3
"""
The panel's built-in colour art (the 88 px and 32 px weather icons and the
solar icon: yellow suns, blue moons and rain, black clouds) as PNG data URIs,
for Switchboard Server's layout preview, so it shows what the panel draws
rather than a one-colour stand-in.

  python3 tools/export_art.py ../Switchboard-Server/public/app/viewport-art.js

Reads the slot table in src/render/icons.cpp and the 4bpp bitmaps in src/kd.
Needs Pillow.
"""
import base64, glob, io, os, re, sys
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')
# The panel's palette as the preview draws it (viewport-preview's k()).
PALETTE = {1: (0x11, 0x11, 0x11), 2: (0xc6, 0x28, 0x28), 3: (0xe0, 0xb4, 0x00), 4: (0x2e, 0x7d, 0x32), 5: (0x15, 0x65, 0xc0)}
WANT = re.compile(r'^(vwx_|vwxm_|ve_solar)')

bitmaps = {}
for f in glob.glob(os.path.join(ROOT, 'src', 'kd', '*.h')):
    for m in re.finditer(r'const\s+uint8_t\s+(\w+)\[\]\s*PROGMEM\s*=\s*\{(.*?)\};', open(f).read(), re.S):
        bitmaps[m.group(1)] = [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(2))]

icons_cpp = open(os.path.join(ROOT, 'src', 'render', 'icons.cpp')).read()
slots = re.findall(r'\{"(\w+)",\s*(\w+),\s*(\d+),\s*true\}', icons_cpp)

def png(bits, size):
    im = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    px = []
    for b in bits:
        px += [b >> 4, b & 15]
    im.putdata([PALETTE[p] + (255,) if p in PALETTE else (0, 0, 0, 0) for p in px[: size * size]])
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()

art, slot_map = {}, {}
for key, name, size in slots:
    if not WANT.match(key):
        continue
    if name not in art:
        art[name] = png(bitmaps[name], int(size))
    slot_map[key] = name

out = ["// Generated by Switchboard-Viewport's tools/export_art.py from the panel's",
       "// built-in art (src/kd): don't edit by hand. The colour weather and solar",
       "// icons a viewport draws when its theme doesn't replace them.",
       "const ART = {"]
out += [f"  {n}: '{u}'," for n, u in art.items()]
out += ["};", "", "const SLOTS = {"]
out += [f"  {k}: '{n}'," for k, n in slot_map.items()]
out += ["};", "", "// The built-in art for an icon slot (vwx_sunny, ve_solar...), or null.",
        "export const builtInArt = (slot) => (SLOTS[slot] ? ART[SLOTS[slot]] : null);", ""]
open(sys.argv[1], 'w').write('\n'.join(out))
print(f'{len(art)} images for {len(slot_map)} slots -> {sys.argv[1]}')
