#!/usr/bin/env node
'use strict';

/**
 * Generates src/render/system_icons.h: the few icons the setup, pairing,
 * update and splash screens draw that the kitchen panel never had, as 1-bit
 * masks in Switchboard's icon format (bit 0 = ink, rows padded to bytes),
 * rasterized from Material Design Icons exactly as Switchboard Server's
 * /api/icons/mdi does — so a theme can replace them the same way.
 *
 *   npm i --no-save @mdi/svg sharp && node tools/gen_icons.js
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const MDI = path.join(path.dirname(require.resolve('@mdi/svg/package.json')), 'svg');
const ICONS = [
  ['LOGO', 'monitor-dashboard', 120],
  ['WIFI', 'wifi', 64],
  ['LINK', 'link-variant', 64],
  ['UPDATE', 'download', 64],
  ['SERVER_OFF', 'server-network-off', 96],
  ['NOT_SET_UP', 'view-dashboard-edit-outline', 96]
];

async function pack(name, size) {
  const svg = fs.readFileSync(path.join(MDI, `${name}.svg`));
  const { data, info } = await sharp(svg, { density: 96 * 4 })
    .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .raw()
    .ensureAlpha()
    .toBuffer({ resolveWithObject: true });
  const rowBytes = Math.ceil(info.width / 8);
  const out = Buffer.alloc(rowBytes * info.height, 0xff);
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      if (data[(y * info.width + x) * 4 + 3] >= 128) out[y * rowBytes + (x >> 3)] &= ~(0x80 >> (x & 7));
    }
  }
  return { w: info.width, h: info.height, bits: out };
}

(async () => {
  let h = `// Generated by tools/gen_icons.js — do not edit.
// 1-bit masks (bit 0 = ink, rows padded to bytes) from Material Design Icons.
#pragma once
#include <stdint.h>
#include "render/pgm.h"

namespace sysicons {
`;
  for (const [id, name, size] of ICONS) {
    const { w, h: ht, bits } = await pack(name, size);
    const hex = [...bits].map((b) => `0x${b.toString(16).padStart(2, '0')}`);
    const rows = [];
    for (let i = 0; i < hex.length; i += 16) rows.push(`  ${hex.slice(i, i + 16).join(', ')},`);
    h += `\n// ${name}, ${w}x${ht}\nconstexpr uint16_t ${id}_W = ${w}, ${id}_H = ${ht};\nstatic const uint8_t ${id}[] PROGMEM = {\n${rows.join('\n')}\n};\n`;
  }
  h += '\n}  // namespace sysicons\n';
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'render', 'system_icons.h'), h);
  console.log('wrote src/render/system_icons.h');
})();
